### ISSUE TITLE
Problems with Haiku

### ISSUE THREAD

**Issue by percypeng5221** [kenjyoung/mctx_learning_demo#4]
I install Haiku through this command:
```
pip install git+https://github.com/deepmind/dm-haiku
```
But I got this error:
```
Traceback (most recent call last):
  File "basic_tree_search.py", line 2, in <module>
    import haiku as hk
  File "/home/percyp/anaconda3/envs/isaac/lib/python3.8/site-packages/haiku/__init__.py", line 19, in <module>
    from haiku import data_structures
  File "/home/percyp/anaconda3/envs/isaac/lib/python3.8/site-packages/haiku/data_structures.py", line 18, in <module>
    from haiku._src.data_structures import to_haiku_dict
  File "/home/percyp/anaconda3/envs/isaac/lib/python3.8/site-packages/haiku/_src/data_structures.py", line 30, in <module>
    from haiku._src import utils
  File "/home/percyp/anaconda3/envs/isaac/lib/python3.8/site-packages/haiku/_src/utils.py", line 42, in <module>
    def auto_repr(cls: type[Any], *args, **kwargs) -> str:
TypeError: 'type' object is not subscriptable
```
Am I installing from the wrong place? Could you help me solve this problem?

**Comment by percypeng5221** [comment]
It seems like using python version >= 3.9 would work!
